### ISSUE TITLE
Time does not reset when switching to another channel

### ISSUE THREAD

**Issue by sitiom** [RazerMoon/vcTimer#1]

**Comment by RazerMoon** [comment]
Thanks, Gonna check this out later.




_Note to self: Remount, FluxDispatcher_

**Comment by RazerMoon** [comment]
Fixed, let me know if you get any more bugs.

![1](https://user-images.githubusercontent.com/33849459/113579057-a915e580-961b-11eb-91a1-fc38b7053f31.gif)

**Comment by sitiom** [comment]
All is working now, thanks!
