### ISSUE TITLE
Time resets when it is not supposed to and vice versa

### ISSUE THREAD

**Issue by sitiom** [RazerMoon/vcTimer#5]
Continuation of #1.

Time does not reset when (should reset):
- Someone else moves me to another channel

Time resets when (should not reset):
- Watching a screen share
- Closing a screen share

**Comment by RazerMoon** [comment]
Latest update should fix those issues, listening for a different dispatch now so let me know if you get any more unwanted behaviour.

Preview:
![1](https://user-images.githubusercontent.com/33849459/114237275-c11e9980-997a-11eb-9fa1-92716c915a44.gif)
